cripto/force-app/main/default/objects/Ativo_da_Carteira__c/Ativo_da_Carteira__c.object-meta.xml
<CustomObject>
    <label>Ativo da Carteira</label>
    <nameField>
        <label>Ativo da Carteira</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ativos das Carteira</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Ativo_da_Carteira__c/fields/Carteira__c.field-meta.xml
<CustomField>
    <fullName>Carteira__c</fullName>
    <label>Carteira</label>
    <referenceTo>Carteira__c</referenceTo>
    <relationshipLabel>Ativos das Carteira</relationshipLabel>
    <relationshipName>Ativos_das_Carteira</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cripto/force-app/main/default/objects/Carteira__c/Carteira__c.object-meta.xml
<CustomObject>
    <label>Carteira</label>
    <nameField>
        <displayFormat>CART-{0000000}</displayFormat>
        <label>Número da Carteita</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carteiras</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Carteira__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Carteiras</relationshipLabel>
    <relationshipName>Carteiras1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cripto/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>It is a market composed of two assets where an investment can be exchanged for one asset</description>
    <label>Mercado</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Mercado__c/fields/MoedaPrimaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaPrimaria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Moeda Primária</label>
    <referenceTo>Moeda__c</referenceTo>
    <relationshipLabel>Mercados</relationshipLabel>
    <relationshipName>Mercados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cripto/force-app/main/default/objects/Mercado__c/fields/MoedaSecundaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaSecundaria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Moeda Secundária</label>
    <referenceTo>Moeda__c</referenceTo>
    <relationshipLabel>Mercados (Moeda Secundária)</relationshipLabel>
    <relationshipName>Mercados1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cripto/force-app/main/default/objects/Moeda__c/Moeda__c.object-meta.xml
<CustomObject>
    <label>Moeda</label>
    <nameField>
        <label>Nome de Moeda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Moedas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requesting a purchase or sale transaction</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}/{MM}/{YYYY}</displayFormat>
        <label>Orders Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Ordem__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Mercado__c.Ativo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Mercado__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/MoedaPrimaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaPrimaria__c</fullName>
    <formula>Mercado__r.MoedaPrimaria__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Moeda Primária</label>
    <type>Text</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/MoedaSecundaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaSecundaria__c</fullName>
    <formula>Mercado__r.MoedaSecundaria__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Moeda Secundária</label>
    <type>Text</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order execution status</description>
    <inlineHelpText>Order execution status</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando</fullName>
                <default>true</default>
                <label>Aguardando</label>
            </value>
            <value>
                <fullName>Executada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Venda com Lucro</fullName>
            </value>
            <value>
                <fullName>Venda com Prejuízo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Identifies whether the order is a buy or sell</description>
    <inlineHelpText>Identifies whether the order is a buy or sell</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/recordTypes/Buy.recordType-meta.xml
<RecordType>
    <fullName>Buy</fullName>
    <active>true</active>
    <description>Purchase-type operation where the primary asset is acquired</description>
    <label>Buy</label>
</RecordType>

cripto/force-app/main/default/classes/OrdemTest.cls
@isTest
public class OrdemTest {
    @TestSetup
    static void makeData(){
        Account account = new Account(Name='Teste');
        insert account;
        Carteira__c carteira = new Carteira__c(Conta__c = account.id);
        insert carteira;
        Ativo_da_Carteira__c ativo_carteira1 = new Ativo_da_Carteira__c(Name='TADA', Carteira__c = carteira.Id);
        insert ativo_carteira1;
        Ativo_da_Carteira__c ativo_carteira2 = new Ativo_da_Carteira__c(Name='TBRL', Carteira__c = carteira.Id);
        insert ativo_carteira2;
        Moeda__c moedaPrimaria = new Moeda__c(Name='ADA');
        Moeda__c moedaSecundaria = new Moeda__c(Name='BRL');
        insert moedaPrimaria;
        insert moedaSecundaria;
        Mercado__c mercado = new Mercado__c(Name='TADA/BRL', MoedaPrimaria__c=moedaPrimaria.Id, MoedaSecundaria__c=moedaSecundaria.Id);
        insert mercado;        
    }
    
    @isTest static void InsereOrdemSemTotal() {
        Mercado__c mercado = [SELECT Id FROM Mercado__c WHERE Name='TADA/BRL' LIMIT 1];
        Carteira__c carteira = [SELECT Id FROM Carteira__c Order By Name desc LIMIT 1];
        Ordem__c ordem = new Ordem__c(Status__c='Aguardando', Type__c='Buy', Quantidade__c=1, Preco__c=10, Mercado__c=mercado.Id, Carteira__c=carteira.Id);
        // Perform test
        Test.startTest();
        Database.SaveResult result = Database.insert(ordem, false);
        Test.stopTest();
        // Verify that the deletion should have been stopped by the trigger,
        // so check that we got back an error.
        system.debug(result);
        System.assert(result.isSuccess());
    } 
    
    @isTest static void InsereOrdemSemQuantidade() {
        Account account = new Account(Name='Teste');
        insert account;
        Carteira__c carteira = new Carteira__c(Conta__c = account.id);
        insert carteira;
        Moeda__c moedaPrimaria = new Moeda__c(Name='ADA');
        Moeda__c moedaSecundaria = new Moeda__c(Name='BRL');
        insert moedaPrimaria;
        insert moedaSecundaria;
        Mercado__c mercado = new Mercado__c(Name='ADA/BRL', MoedaPrimaria__c=moedaPrimaria.Id, MoedaSecundaria__c=moedaSecundaria.Id);
        insert mercado; 
        Ordem__c ordem = new Ordem__c(Status__c='Aguardando', Type__c='Buy', Total__c=100, Preco__c=10, Mercado__c=mercado.Id, Carteira__c=carteira.Id);
        // Perform test
        Test.startTest();
        Database.SaveResult result = Database.insert(ordem, false);
        Test.stopTest();
        // Verify that the deletion should have been stopped by the trigger,
        // so check that we got back an error.
        system.debug(result);
        System.assert(result.isSuccess());
    }
    
    @isTest static void InsereOrdemSemQuantidadeeTotal() {
        Account account = new Account(Name='Teste');
        insert account;
        Carteira__c carteira = new Carteira__c(Conta__c = account.id);
        insert carteira;
        Moeda__c moedaPrimaria = new Moeda__c(Name='ADA');
        Moeda__c moedaSecundaria = new Moeda__c(Name='BRL');
        insert moedaPrimaria;
        insert moedaSecundaria;
        Mercado__c mercado = new Mercado__c(Name='ADA/BRL', MoedaPrimaria__c=moedaPrimaria.Id, MoedaSecundaria__c=moedaSecundaria.Id);
        insert mercado; 
        Ordem__c ordem = new Ordem__c(Status__c='Aguardando', Type__c='Buy', Preco__c=10, Mercado__c=mercado.Id, Carteira__c=carteira.Id);
        // Perform test
        Test.startTest();
        Database.SaveResult result = Database.insert(ordem, false);
        Test.stopTest();
        // Verify that the deletion should have been stopped by the trigger,
        // so check that we got back an error.
        system.debug(result);
        System.assert(!result.isSuccess());
    }

    @isTest static void InsereOrdemSemPreco() {
        Account account = new Account(Name='Teste');
        insert account;
        Carteira__c carteira = new Carteira__c(Conta__c = account.id);
        insert carteira;
        Moeda__c moedaPrimaria = new Moeda__c(Name='ADA');
        Moeda__c moedaSecundaria = new Moeda__c(Name='BRL');
        insert moedaPrimaria;
        insert moedaSecundaria;
        Mercado__c mercado = new Mercado__c(Name='ADA/BRL', MoedaPrimaria__c=moedaPrimaria.Id, MoedaSecundaria__c=moedaSecundaria.Id);
        insert mercado; 
        Ordem__c ordem = new Ordem__c(Status__c='Aguardando', Type__c='Buy', Total__c=100, Quantidade__c=10, Mercado__c=mercado.Id, Carteira__c=carteira.Id);
        // Perform test
        Test.startTest();
        Database.SaveResult result = Database.insert(ordem, false);
        Test.stopTest();
        // Verify that the deletion should have been stopped by the trigger,
        // so check that we got back an error.
        system.debug(result);
        System.assert(!result.isSuccess());
    }
    
    @isTest static void AlterarTotal() {
        Account account = new Account(Name='Teste');
        insert account;
        Carteira__c carteira = new Carteira__c(Conta__c = account.id);
        insert carteira;
        Moeda__c moedaPrimaria = new Moeda__c(Name='ADA');
        Moeda__c moedaSecundaria = new Moeda__c(Name='BRL');
        insert moedaPrimaria;
        insert moedaSecundaria;
        Mercado__c mercado = new Mercado__c(Name='ADA/BRL', MoedaPrimaria__c=moedaPrimaria.Id, MoedaSecundaria__c=moedaSecundaria.Id);
        insert mercado; 
        Ordem__c ordem = new Ordem__c(Status__c='Aguardando', Type__c='Buy', Total__c=100, Quantidade__c=10, Preco__c=1, Mercado__c=mercado.Id, Carteira__c=carteira.Id);
        insert ordem;
        //Altera o total da ordem
        ordem.Total__c = 1000;
        // Perform test
        Test.startTest();
        Database.SaveResult result = Database.update(ordem, false);
        Test.stopTest();
        // Verify that the deletion should have been stopped by the trigger,
        // so check that we got back an error.
        system.debug(result);
        System.assert(!result.isSuccess());
    }
    
    @isTest static void IncluiOrdemSemSaldo() {
        Account account = new Account(Name='Teste');
        insert account;
        Carteira__c carteira = new Carteira__c(Conta__c = account.id);
        insert carteira;
        Ativo_da_Carteira__c ativo_carteira1 = new Ativo_da_Carteira__c(Name='ADA', Carteira__c = carteira.Id);
        insert ativo_carteira1;
        Ativo_da_Carteira__c ativo_carteira2 = new Ativo_da_Carteira__c(Name='BRL', Carteira__c = carteira.Id);
        insert ativo_carteira2;
        Moeda__c moedaPrimaria = new Moeda__c(Name='ADA');
        Moeda__c moedaSecundaria = new Moeda__c(Name='BRL');
        insert moedaPrimaria;
        insert moedaSecundaria;
        Mercado__c mercado = new Mercado__c(Name='ADA/BRL', MoedaPrimaria__c=moedaPrimaria.Id, MoedaSecundaria__c=moedaSecundaria.Id);
        insert mercado; 
        Ordem__c ordemCompra = new Ordem__c(Status__c='Executada', Type__c='Buy', Total__c = 10, Quantidade__c=1, Preco__c=10, Mercado__c=mercado.Id, Carteira__c=carteira.Id);
        Test.startTest();
        Database.SaveResult result = Database.insert(ordemCompra, false);
        Test.stopTest();
        // Verify that the deletion should have been stopped by the trigger,
        // so check that we got back an error.
        system.debug('mensagem : ' + result.getErrors()[0].getMessage());
        System.assert(!result.isSuccess());
        System.assertEquals('Saldo Insuficiente.', result.getErrors()[0].getMessage());
    }
}