cripto/force-app/main/default/objects/Ativo_da_Carteira__c/Ativo_da_Carteira__c.object-meta.xml
<CustomObject>
    <label>Ativo da Carteira</label>
    <nameField>
        <label>Ativo da Carteira</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ativos das Carteira</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Ativo_da_Carteira__c/fields/Carteira__c.field-meta.xml
<CustomField>
    <fullName>Carteira__c</fullName>
    <label>Carteira</label>
    <referenceTo>Carteira__c</referenceTo>
    <relationshipLabel>Ativos das Carteira</relationshipLabel>
    <relationshipName>Ativos_das_Carteira</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cripto/force-app/main/default/objects/Carteira__c/Carteira__c.object-meta.xml
<CustomObject>
    <label>Carteira</label>
    <nameField>
        <displayFormat>CART-{0000000}</displayFormat>
        <label>Número da Carteita</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carteiras</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Carteira__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Carteiras</relationshipLabel>
    <relationshipName>Carteiras1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cripto/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>It is a market composed of two assets where an investment can be exchanged for one asset</description>
    <label>Mercado</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Mercado__c/fields/MoedaPrimaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaPrimaria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Moeda Primária</label>
    <referenceTo>Moeda__c</referenceTo>
    <relationshipLabel>Mercados</relationshipLabel>
    <relationshipName>Mercados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cripto/force-app/main/default/objects/Mercado__c/fields/MoedaSecundaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaSecundaria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Moeda Secundária</label>
    <referenceTo>Moeda__c</referenceTo>
    <relationshipLabel>Mercados (Moeda Secundária)</relationshipLabel>
    <relationshipName>Mercados1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cripto/force-app/main/default/objects/Moeda__c/Moeda__c.object-meta.xml
<CustomObject>
    <label>Moeda</label>
    <nameField>
        <label>Nome de Moeda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Moedas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cripto/force-app/main/default/classes/HistoricoPrecosTest.cls
@isTest
public class HistoricoPrecosTest {
    @TestSetup
    static void makeData(){
        Account account = new Account(Name='Teste');
        insert account;
        Carteira__c carteira = new Carteira__c(Conta__c = account.id);
        insert carteira;
        Ativo_da_Carteira__c ativoCarteira1 = new Ativo_da_Carteira__c(Name='TADA', Carteira__c = carteira.Id);
        insert ativoCarteira1;
        Ativo_da_Carteira__c ativoCarteira2 = new Ativo_da_Carteira__c(Name='TBRL', Carteira__c = carteira.Id);
        insert ativoCarteira2;
        Moeda__c moedaPrimaria = new Moeda__c(Name='TADA');
        Moeda__c moedaSecundaria = new Moeda__c(Name='TBRL');
        insert moedaPrimaria;
        insert moedaSecundaria;
        Mercado__c mercado = new Mercado__c(Name='TADA/TBRL', MoedaPrimaria__c=moedaPrimaria.Id, MoedaSecundaria__c=moedaSecundaria.Id);
        insert mercado;      
    }

    @isTest 
    static void inserePrecosEmMassa() {
        List<Historico_de_Precos__c> listHistorico = new List<Historico_de_Precos__c>();
        Mercado__c mercado = [SELECT Id FROM Mercado__c WHERE Name='TADA/TBRL' LIMIT 1];
        for(integer i = 0; i <= 300; i++) {
            listHistorico.add(new Historico_de_Precos__c(Mercado__c=mercado.id, Preco__c=i*10));
        }

        Test.startTest();
        Database.SaveResult[] results = Database.insert(listHistorico, false);
        Test.stopTest();        

        for (Database.SaveResult result : results){
            System.assert(result.isSuccess());
        }
    }
}