cripto/force-app/main/default/objects/Ativo_da_Carteira__c/Ativo_da_Carteira__c.object-meta.xml
<CustomObject>
    <label>Ativo da Carteira</label>
    <nameField>
        <label>Ativo da Carteira</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ativos das Carteira</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Ativo_da_Carteira__c/fields/Carteira__c.field-meta.xml
<CustomField>
    <fullName>Carteira__c</fullName>
    <label>Carteira</label>
    <referenceTo>Carteira__c</referenceTo>
    <relationshipLabel>Ativos das Carteira</relationshipLabel>
    <relationshipName>Ativos_das_Carteira</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cripto/force-app/main/default/objects/Ativo_da_Carteira__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <label>Saldo</label>
    <summarizedField>Transacao__c.Quantidade__c</summarizedField>
    <summaryForeignKey>Transacao__c.Ativo_da_Carteira__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

cripto/force-app/main/default/objects/Carteira__c/Carteira__c.object-meta.xml
<CustomObject>
    <label>Carteira</label>
    <nameField>
        <displayFormat>CART-{0000000}</displayFormat>
        <label>Número da Carteita</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carteiras</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requesting a purchase or sale transaction</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}/{MM}/{YYYY}</displayFormat>
        <label>Orders Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Ordem__c/fields/MoedaPrimaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaPrimaria__c</fullName>
    <formula>Mercado__r.MoedaPrimaria__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Moeda Primária</label>
    <type>Text</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/MoedaSecundaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaSecundaria__c</fullName>
    <formula>Mercado__r.MoedaSecundaria__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Moeda Secundária</label>
    <type>Text</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order execution status</description>
    <inlineHelpText>Order execution status</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando</fullName>
                <default>true</default>
                <label>Aguardando</label>
            </value>
            <value>
                <fullName>Executada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Venda com Lucro</fullName>
            </value>
            <value>
                <fullName>Venda com Prejuízo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Identifies whether the order is a buy or sell</description>
    <inlineHelpText>Identifies whether the order is a buy or sell</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/recordTypes/Buy.recordType-meta.xml
<RecordType>
    <fullName>Buy</fullName>
    <active>true</active>
    <description>Purchase-type operation where the primary asset is acquired</description>
    <label>Buy</label>
</RecordType>

cripto/force-app/main/default/classes/OrdemDomain.cls
public with sharing class OrdemDomain {
    private Ordem__c ordem;
    private List<Ativo_da_Carteira__c> ativosCarteiras;

    public OrdemDomain(Ordem__c ordem) {
        this.ordem = ordem;
    }

    public void recalculaTotal() {
        this.validaQuantidade();   
        this.validaPreco();   
        this.ordem.Total__c = this.ordem.Quantidade__c * this.ordem.Preco__c;
    }

    public void recalculaQuantidade(){
        this.validaPreco(); 
        if (this.isFieldNull(Schema.Ordem__c.Total__c))
        {
            this.ordem.Quantidade__c = this.ordem.Total__c / this.ordem.Preco__c; 
        }   
    }

    public void validaPreco()
    {
        if(this.isFieldNull(Schema.Ordem__c.Preco__c)) {
            this.ordem.addError('Preço deve ser informado');    
        }
    }

    public void validaQuantidade()
    {
        if(this.isFieldNull(Schema.Ordem__c.Quantidade__c)) {
            this.ordem.addError('Quantidade deve ser informado');    
        }
    }  

    public void verificaSaldo()
    {
        if (this.ordem.Status__c == 'Executada') {
            if ((this.ativosCarteiras == null)||(this.ativosCarteiras.size() == 0)) {
                this.ativosCarteiras = [select Carteira__c, Name, saldo__c from Ativo_da_Carteira__c];
            }
            
            decimal quantidade = ((this.ordem.Type__c == 'Buy') ? this.ordem.Total__c : this.ordem.Quantidade__c);
            decimal saldo = getSaldoMoedaCarteira(((this.ordem.Type__c == 'Buy') ? this.ordem.MoedaSecundaria__c : this.ordem.MoedaPrimaria__c), this.ordem.Carteira__c);
            if (saldo - quantidade < 0) {
                this.ordem.addError('Saldo Insuficiente.');
            }  
        }
    }

    private decimal getSaldoMoedaCarteira(String moeda, id carteira) {
        decimal saldo = 0;
        for (Ativo_da_Carteira__c ativoCarteira : this.ativosCarteiras) {
            if ((ativoCarteira.Name == moeda) && (ativoCarteira.Carteira__c == carteira)) {
                saldo = ativoCarteira.saldo__c;
                break;
            }
        }
        return saldo;
    }

    public Boolean isFieldDifferent(sObjectField field, Ordem__c compareOrder) {
        return ordem.get(field) != compareOrder.get(field);
    }

    public Boolean isFieldNull(sObjectField field) {
        return ordem.get(field) == null;
    }

}