cripto/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requesting a purchase or sale transaction</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}/{MM}/{YYYY}</displayFormat>
        <label>Orders Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Ordem__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

cripto/force-app/main/default/classes/OrdemTriggerHandler.cls
public with sharing class OrdemTriggerHandler extends TriggerHandler
{
    public OrdemTriggerHandler() {}

    protected override void beforeInsert()
    {
        for (Ordem__c o : (List<Ordem__c>)Trigger.New)
        {
            OrdemDomain ordem = new OrdemDomain(o);    
            ordem.verificaSaldo();
            if(ordem.isFieldNull(Schema.Ordem__c.Total__c)) {
                ordem.RecalculaTotal();
            } else {
                ordem.RecalculaQuantidade();
            }
        }
    }

    protected override void beforeUpdate()
    {
        for (Ordem__c o : (List<Ordem__c>)Trigger.New)
        {
            OrdemDomain ordem = new OrdemDomain(o); 
            ordem.verificaSaldo();

            Ordem__c oOld = (Ordem__c)Trigger.oldMap.get(o.Id);
            if(ordem.isFieldDifferent(Schema.Ordem__c.Total__c, oOld)){
                o.addError('O Total não pode ser alterado');
            }

            if(ordem.isFieldDifferent(Schema.Ordem__c.Quantidade__c, oOld)||
               ordem.isFieldDifferent(Schema.Ordem__c.Preco__c, oOld) ){
                ordem.validaQuantidade();   
                ordem.validaPreco(); 
                ordem.RecalculaTotal();
            }
        }
    }
}