cripto/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>It is a market composed of two assets where an investment can be exchanged for one asset</description>
    <label>Mercado</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Mercado__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>true</defaultValue>
    <description>It means that the market is active for new orders</description>
    <inlineHelpText>It means that the market is active for new orders</inlineHelpText>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

cripto/force-app/main/default/objects/Mercado__c/fields/MoedaPrimaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaPrimaria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Moeda Primária</label>
    <referenceTo>Moeda__c</referenceTo>
    <relationshipLabel>Mercados</relationshipLabel>
    <relationshipName>Mercados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cripto/force-app/main/default/objects/Mercado__c/fields/MoedaSecundaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaSecundaria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Moeda Secundária</label>
    <referenceTo>Moeda__c</referenceTo>
    <relationshipLabel>Mercados (Moeda Secundária)</relationshipLabel>
    <relationshipName>Mercados1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cripto/force-app/main/default/objects/Moeda__c/Moeda__c.object-meta.xml
<CustomObject>
    <label>Moeda</label>
    <nameField>
        <label>Nome de Moeda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Moedas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requesting a purchase or sale transaction</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}/{MM}/{YYYY}</displayFormat>
        <label>Orders Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Ordem__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Mercado__c.Ativo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Mercado__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/MoedaPrimaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaPrimaria__c</fullName>
    <formula>Mercado__r.MoedaPrimaria__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Moeda Primária</label>
    <type>Text</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/MoedaSecundaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaSecundaria__c</fullName>
    <formula>Mercado__r.MoedaSecundaria__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Moeda Secundária</label>
    <type>Text</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

cripto/force-app/main/default/classes/BinanceApi.cls
public with sharing class BinanceApi {
    public BinanceApi() {
    }

    @AuraEnabled
    public static String getRecordTypeId(String orderType){
        String rTypeId = Schema.SObjectType.Ordem__c.getRecordTypeInfosByDeveloperName().get(orderType).getRecordTypeId();
        return rTypeId;
    }

    @AuraEnabled
    public static String getPrice(String mercadoId){
        try {
            Mercado__c mercado = [SELECT id, MoedaPrimaria__c, MoedaSecundaria__c from Mercado__c where id = :mercadoId];
            Moeda__c moedaPrimaria = [select Name from Moeda__c where id = :mercado.MoedaPrimaria__c];
            Moeda__c moedaSecundaria = [select Name from Moeda__c where id = :mercado.MoedaSecundaria__c];
            String pair = moedaPrimaria.Name + moedaSecundaria.Name;
            pair = pair.replace('USD', 'USDT');
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint('https://api.binance.com/api/v3/ticker/price?symbol=' + pair);
            request.setMethod('GET');
            HttpResponse response = http.send(request);
            if (response.getStatusCode() == 200) {
                system.debug(response.getBody());
                SymbolPrice sp = (SymbolPrice)JSON.deserialize(response.getBody(), SymbolPrice.class);
                return String.valueOf(sp.price);
            } else {
                return 'Erro ao acessar a API do Binance';
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @future (callout=true)
    public static void getPrice(){
        try {
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint('https://api.binance.com/api/v3/ticker/price');
            request.setMethod('GET');
            HttpResponse response = http.send(request);
            if (response.getStatusCode() == 200) {
                List<SymbolPrice> spList = (List<SymbolPrice>)JSON.deserialize(response.getBody(), List<SymbolPrice>.class);
        
                Map<String, decimal> priceMap = new Map<String, decimal>();
                for(BinanceApi.SymbolPrice sp : spList){
                    priceMap.put(sp.symbol, sp.price);
                }
                
                List<Historico_de_Precos__c> historicoList = new List<Historico_de_Precos__c>();
                for(Mercado__c mercado : [SELECT ID, Pair__c 
                                                  FROM Mercado__c 
                                                 WHERE Ativo__c = true 
                                                   AND Pair__c in :priceMap.keySet()]){
                    historicoList.add(new Historico_de_Precos__c(Mercado__c = mercado.Id, Preco__c = priceMap.get(mercado.Pair__c)));
                }

                if(historicoList.size()>0){
                    insert historicoList;
                }  
            }             
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public Class SymbolPrice{
        public String symbol;
        public decimal price;
    }
}