cripto/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>It is a market composed of two assets where an investment can be exchanged for one asset</description>
    <label>Mercado</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requesting a purchase or sale transaction</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}/{MM}/{YYYY}</displayFormat>
        <label>Orders Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Ordem__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Mercado__c.Ativo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Mercado__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order execution status</description>
    <inlineHelpText>Order execution status</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando</fullName>
                <default>true</default>
                <label>Aguardando</label>
            </value>
            <value>
                <fullName>Executada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Venda com Lucro</fullName>
            </value>
            <value>
                <fullName>Venda com Prejuízo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Identifies whether the order is a buy or sell</description>
    <inlineHelpText>Identifies whether the order is a buy or sell</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cripto/force-app/main/default/classes/VFOrdemController.cls
public class VFOrdemController {
    public List<Ordem__c> ordemList {get; set; }
    public String cotacao_atual {get; set; }
    public Transient List<BinanceApi.SymbolPrice> spList {get; set; }
    public DateTime dataAtual {get; set; }

    public VFOrdemController() {

    }

    public VFOrdemController(ApexPages.StandardController controller) {
        Mercado__c mercado = (Mercado__c)controller.getRecord();
        ordemList = [SELECT Id, Name, OperacaoMercado__c, toLabel(Type__c), Status__c, Quantidade__c, Preco__c, Total__c , ValidadeOrdem__c
                       FROM Ordem__c 
                      WHERE Mercado__c = :mercado.id];

        for(Ordem__c o : ordemList) {
           o.Quantidade__c = o.Quantidade__c.setScale(6);
           o.Total__c = o.Total__c.setScale(6);
        }
                    
        cotacao_atual = BinanceApi.getPrice(mercado.id);
        spList = BinanceApi.getPrice();

        for(BinanceApi.SymbolPrice sp : spList) {
            sp.price = sp.price.setScale(6);
         }

         dataAtual = DateTime.now();
    }

}