cripto/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>It is a market composed of two assets where an investment can be exchanged for one asset</description>
    <label>Mercado</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requesting a purchase or sale transaction</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}/{MM}/{YYYY}</displayFormat>
        <label>Orders Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cripto/force-app/main/default/objects/Ordem__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Mercado__c.Ativo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Mercado__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

cripto/force-app/main/default/objects/Ordem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order execution status</description>
    <inlineHelpText>Order execution status</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando</fullName>
                <default>true</default>
                <label>Aguardando</label>
            </value>
            <value>
                <fullName>Executada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Venda com Lucro</fullName>
            </value>
            <value>
                <fullName>Venda com Prejuízo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cripto/force-app/main/default/classes/MercadoTriggerHandler.cls
public with sharing class MercadoTriggerHandler extends TriggerHandler {
    public MercadoTriggerHandler() {
    }

    protected override void afterUpdate() 
    {
        this.executaOrdem();
    }

    private void executaOrdem(){
        List<Ordem__c> listUpdate = new List<Ordem__c>();
        for(Ordem__c ordem : [select id, Preco__c, Mercado__c  
                                from Ordem__c 
                               where Mercado__c in :Trigger.newMap.keySet() 
                                 and status__c = 'Aguardando']){
            decimal precoNovo = recuperaPrecoNovo(ordem.Mercado__c);
            decimal precoAntigo = recuperaPrecoAntigo(ordem.Mercado__c);     
            if(precoAntigo<>precoNovo) {
                if((ordem.Preco__c >= precoAntigo && ordem.Preco__c <= precoNovo) || (ordem.Preco__c <= precoAntigo && ordem.Preco__c >= precoNovo)) 
                {
                    listUpdate.add(new Ordem__c(id=ordem.id, status__c = 'Executada', Preco__c = precoNovo));
                }
            } 
        }

        if(listUpdate.size()>0){
            update listUpdate;
        }
    }

    private decimal recuperaPrecoNovo(string id) {
        Mercado__c m = (Mercado__c)trigger.newMap.get(id);
        return m.CotacaoAtual__c;
    }

    private decimal recuperaPrecoAntigo(string id) {
        Mercado__c m = (Mercado__c)trigger.oldMap.get(id);
        return m.CotacaoAtual__c;
    }
}